spring.datasource.url=jdbc:postgresql://<HOST>:5432/<DB_NAME>
spring.datasource.username=andinaadmin
spring.datasource.password=1597532486147Gey

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
